### ISSUE TITLE
"Unable to find libfuse" in MacOS

### ISSUE THREAD

**Issue by YuPototo** [mobilecoinofficial/forest#218]
I tried to run hellobot with:

`poetry run python -m sample_bots.hellobot`

And an exception is raised:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/qinyu/job/alf/singal_bot/forestbot-template/template.py", line 1, in <module>
    from forest.core import Bot, Message, run_bot
  File "/Users/qinyu/Library/Caches/pypoetry/virtualenvs/yourbot-1I-L8FrT-py3.9/lib/python3.9/site-packages/forest/core.py", line 43, in <module>
    from forest import autosave, datastore, payments_monitor, pghelp, utils, string_dist
  File "/Users/qinyu/Library/Caches/pypoetry/virtualenvs/yourbot-1I-L8FrT-py3.9/lib/python3.9/site-packages/forest/autosave.py", line 16, in <module>
    from forest import fuse, mem, utils
  File "/Users/qinyu/Library/Caches/pypoetry/virtualenvs/yourbot-1I-L8FrT-py3.9/lib/python3.9/site-packages/forest/fuse.py", line 56, in <module>
    raise EnvironmentError("Unable to find libfuse")
OSError: Unable to find libfuse
```

I failed to google a solution to this problem. Any thoughts?

**Comment by cxloe** [comment]
Are you using MacPorts or Homebrew?

**Comment by YuPototo** [comment]
> Are you using MacPorts or Homebrew?

I have installed programs with Homebrew. I don't think that I have used MacPorts.
